packages:
 - !include common/openamber.yaml

esp32:
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHZ
  framework:
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "16384"

esphome:
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio

uart:
  rx_pin:
    number: GPIO43
    inverted: False
  tx_pin:
    number: GPIO44
    inverted: False

psram:
  mode: octal
  speed: 80MHz

ch422g:
  - id: ch422g_hub

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: False
  frequency: 400kHz

display:
  - platform: mipi_rgb
    model: WAVESHARE-5-1024X600
    id: my_display

switch:
  - platform: gpio
    name: backlight switch
    pin:
      ch422g: ch422g_hub
      number: 2
    restore_mode: ALWAYS_ON
    internal: true

globals:
  - id: is_idled
    type: bool

touchscreen:
  - platform: gt911
    address: 0x5D
    id: my_touchscreen
    interrupt_pin: GPIO4
    reset_pin:
      ch422g: ch422g_hub
      number: 1
    on_release:
      - if:
          condition:
            lambda: 'return (id(is_idled) == true);'
          then:
            - globals.set:
                id: is_idled
                value: 'false'
            - lvgl.widget.hide:
                id: idle_screen_overlay

interval:
 - interval: 5s
   then: !include lvgl/ui_update_loop.yaml

image:
  - file: "lvgl/images/water_circuit.png"
    id: img_water_circuit
    type: RGB565
    transparency: alpha_channel
    resize: 420x420

font: !include lvgl/fonts.yaml

lvgl:
  on_idle:
    - timeout: 60s
      then:
        - globals.set:
            id: is_idled
            value: 'true'
        - lvgl.widget.show:
            id: idle_screen_overlay
  disp_bg_color: 0x0A2747
  widgets:
    - !include lvgl/root_bg.yaml
    - !include lvgl/header_bar.yaml
    - !include lvgl/page_home.yaml
    - !include lvgl/nav_bar.yaml
    - !include lvgl/boot_screen.yaml
    - !include lvgl/idle_screen_overlay.yaml